heat_template_version: 2016-04-08

description: This template deploys a standard f5 standalone BIG-IP VE - 1NIC.

parameters:
  bigip_image:
    type: string
    label: f5 BIG-IP VE Image
    description: The BIG-IP VE image to be used on the compute instance.
    constraints:
      - custom_constraint: glance.image
  bigip_flavor:
    type: string
    label: f5 BIG-IP VE Flavor
    description: Type of instance (flavor) to be used for the VE.
    constraints:
      - custom_constraint: nova.flavor
  use_config_drive:
    type: boolean
    label: Use Config Drive
    description: Use config drive to provide meta and user data.
    default: false
  libs_proxy_protocol:
    type: string
    label: Proxy Protocol to use when downloading onboarding libs
    description: Use specified protocol when downloading libs through a proxy
    default: None
  libs_proxy_host:
    type: string
    label: Proxy Host to use when downloading onboarding libs
    description: Use specified host when downloading libs through a proxy
    default: None
  libs_proxy_port:
    type: string
    label: Proxy Port to use when downloading libs
    description: Use specified port when downloading onboarding libs through a proxy
    default: None
  libs_proxy_auth:
    type: string
    label: Basic Proxy Authentication
    description: Default auth value in the format <username:password> for downloading onboarding libs through a proxy
    hidden: true
    default: None
  libs_proxy_addtl_opts:
    type: string
    label: Additional Proxy Options
    description: Additional parameters to add to onboarding libs download request with proxy
    default: None
  f5_cloudlibs_tag:
    type: string
    label: f5 CloudLibs Tag
    description: Tag that determines version of f5 cloudlibs to use for provisioning. If specified, ensure that hashes are valid by either updating scripts/verifyHash or by providing a f5_cloudlibs_verify_hash_url_override value.
    default: v4.0.3
  f5_cloudlibs_url_override:
    type: string
    label: f5 cloud-libs URL Override
    description: Alternate URL for f5-cloud-libs package. If not specified, the default GitHub location for f5-cloud-libs will be used. If version is different from default f5_cloudlibs_tag, ensure that hashes are valid by either updating scripts/verifyHash or by providing a f5_cloudlibs_verify_hash_url_override value.
    default: None
  f5_cloudlibs_verify_hash_url_override:
    type: string
    label: f5 cloud-libs verifyHash URL Override
    description: Alternate URL for verifyHash used to validate f5-cloud-libs package. If not specified, the scripts/verifyHash will be used.
    default: None
  f5_cloudlibs_openstack_tag:
    type: string
    label: f5-cloud-libs-openstack Tag
    description: Tag that determines version of f5 cloudlibs-package to use for provisioning. If specified, ensure that hashes are valid by either updating scripts/verifyHash or by providing a f5_cloudlibs_verify_hash_url_override value.
    default: v2.0.0
  f5_cloudlibs_openstack_url_override:
    type: string
    label: f5-cloud-libs-openstack URL Override
    description: Alternate URL for f5-cloud-libs-openstack package. If not specified, the default GitHub location for f5-cloud-libs will be used. If version is different from default f5_cloudlibs_tag, ensure that hashes are valid by either updating scripts/verifyHash or by providing a f5_cloudlibs_verify_hash_url_override value.
    default: None

  bigip_servers_ntp:
    type: comma_delimited_list
    label: f5 BIG-IP VE NTP servers
    description: A list of NTP servers to configure on the BIG-IP.
    default:
      - 0.us.pool.ntp.org
      - 1.us.pool.ntp.org
  bigip_timezone:
    type: string
    label: f5 BIG-IP VE NTP timezone
    description: The NTP timezone to configure on the BIG-IP
    default: UTC
  bigip_remote_hosts_names:
    type: comma_delimited_list
    label: f5 BIG-IP VE Remote Host Names
    description: A list of remote hosts to add to the BIG-IP
    default:
      -
  bigip_remote_hosts_ips:
    type: comma_delimited_list
    label: f5 BIG-IP VE Remote Host IP Addresses
    description: A list of remote host ips to add to the BIG-IP. The index should match the entries provided in bigip_remote_hosts_names
    default:
      -
  bigip_servers_dns:
    type: comma_delimited_list
    label: f5 BIG-IP VE Domain Name Servers
    description: A list of DNS servers to configure on the BIG-IP.
    default:
      -
  allow_usage_analytics:
    type: boolean
    label: Allow Usage Analytics
    description: Toggles whether non-identifiable statistical information is sent to F5.
    default: true

  #bigip credentials
  bigip_os_ssh_key:
    type: string
    label: f5 BIG-IP VE Root SSH Key Name
    description: Name of key-pair to be installed on the BIG-IP VE instance to allow root SSH access.
    constraints:
      - custom_constraint: nova.keypair
  bigip_admin_pwd:
    type: string
    label: f5 BIG-IP VE Admin User Password
    description: Password for the BIG-IP admin user.
    hidden: true
  bigip_root_pwd:
    type: string
    label: f5 BIG-IP VE Root User Password
    description: Password for the BIG-IP root user.
    hidden: true
  #bigip licensing
  bigip_licensing_type:
    type: string
    label: BIG-IP Licensing Type
    description: Type of licensing to use for BIG-IP. Allowed values are BYOL (License Key), or NO_LIC (skip licensing).
    constraints:
      - allowed_values:
          - BYOL
          - NO_LIC
  bigip_license_key:
    type: string
    label: Primary BIG-IP VE License Base Key
    description: f5 BIG-IP License Base Key.
    default: None
  bigip_addon_license_keys:
    type: comma_delimited_list
    label: Additional BIG-IP VE License Keys
    description: f5 BIG-IP License Add-On Keys.
    default:
      -
  bigip_modules:
    type: comma_delimited_list
    label: Modules to provision on the BIG-IP.
    description: A list modules to provision and their level. <module_name:level>
    default:
      - ltm:nominal
  #os network
  external_network:
    type: string
    label: External Network Name
    description: Name of external network where floating IP resides.
    constraints:
      - custom_constraint: neutron.network
  mgmt_network:
    type: string
    label: Management Network
    description: Network to which the BIG-IP management interface is attached.
    constraints:
      - custom_constraint: neutron.network
  mgmt_security_group_name:
    type: string
    label: Management Security Group Name
    description: Name to apply on the security group for the BIG-IP management network.
  #bigip network
  bigip_mgmt_port:
    type: number
    label: Management port
    description: Port for the BIG-IP Management uri
    default: 8443

  #os heat
  os_heat_wc_notify_options:
    type: string
    label: Additional Heat Wait Condition Notify Curl Options
    description: Additional options for the heat wait condition signals sent via curl
    default: None


parameter_groups:
  - label: BIG-IP General Provisioning
    parameters:
      - bigip_image
      - bigip_flavor
      - use_config_drive
      - libs_proxy_protocol
      - libs_proxy_host
      - libs_proxy_port
      - libs_proxy_auth
      - libs_proxy_addtl_opts
      - f5_cloudlibs_tag
      - f5_cloudlibs_url_override
      - f5_cloudlibs_verify_hash_url_override
      - f5_cloudlibs_openstack_tag
      - f5_cloudlibs_openstack_url_override
      - bigip_servers_ntp
      - bigip_timezone
      - bigip_servers_dns
      - bigip_remote_hosts_names
      - bigip_remote_hosts_ips
      - allow_usage_analytics
  - label: BIG-IP Credentials
    parameters:
      - bigip_os_ssh_key
      - bigip_admin_pwd
      - bigip_root_pwd
  - label: BIG-IP Licensing and Modules
    parameters:
      - bigip_licensing_type
      - bigip_license_key
      - bigip_addon_license_keys
      - bigip_modules
  - label: OS Network
    parameters:
      - external_network
      - mgmt_network
      - mgmt_security_group_name
  - label: BIG-IP Network
    parameters:
      - bigip_mgmt_port
  - label: OS Heat
    parameters:
      - os_heat_wc_notify_options

resources:
  wait_condition_onboard_complete:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: wait_handle_onboard}
      count: 3
      timeout: 1800
  wait_handle_onboard:
    type: OS::Heat::WaitConditionHandle
  mgmt_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: mgmt_network }
      security_groups: [{ get_attr: [mgmt_security_group, data_security_group_id] }]
      allowed_address_pairs:
        - ip_address: 0.0.0.0/0
        - ip_address: ::/0
  # In 1NIC, management also acts as data plane, so default to data sec group rules
  mgmt_security_group:
    type: F5::BigIP::DataSecurityGroup
    properties:
      security_group_name: { get_param: mgmt_security_group_name }
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network }
      port_id: { get_resource: mgmt_port }
  init_1_override_default_config:
    type: F5::BigIP::OverrideDefaultConfig
    properties:
      disable_1nic_autoconfig: false
      admin_password: { get_param: bigip_admin_pwd }
      root_password: { get_param: bigip_root_pwd }
  init_2_onboard_libs:
    type: F5::BigIP::OnboardingLibs
    properties:
      libs_proxy_protocol: { get_param: libs_proxy_protocol }
      libs_proxy_host: { get_param: libs_proxy_host }
      libs_proxy_port: { get_param: libs_proxy_port }
      libs_proxy_auth: { get_param: libs_proxy_auth }
      libs_proxy_addtl_opts: { get_param: libs_proxy_addtl_opts }
      cloudlibs_tag: { get_param: f5_cloudlibs_tag }
      cloudlibs_url_override: { get_param: f5_cloudlibs_url_override }
      cloudlibs_os_tag: { get_param: f5_cloudlibs_openstack_tag }
      cloudlibs_os_url_override: { get_param: f5_cloudlibs_openstack_url_override }
  init_3_onboard_scripts:
    type: F5::BigIP::OnboardingScripts
    properties:
      verify_hash_url_override: { get_param: f5_cloudlibs_verify_hash_url_override}
      bigip_addon_licenses: { get_param: bigip_addon_license_keys }
      bigip_license: { get_param: bigip_license_key }
      modules: { get_param: bigip_modules }
      ntp: { get_param: bigip_servers_ntp }
      timezone: { get_param: bigip_timezone }
      dns: { get_param: bigip_servers_dns }
      remote_hosts_names: { get_param: bigip_remote_hosts_names }
      remote_hosts_ips: { get_param: bigip_remote_hosts_ips }
      host_name: { get_attr: [mgmt_port, show, dns_assignment, 0, fqdn] }
      management_port_id: { get_resource: mgmt_port }
      management_port: { get_param: bigip_mgmt_port }
      db_vars:
        - provision.1nicautoconfig:disable
      ssh_key_name: { get_param: bigip_os_ssh_key }
      use_config_drive: { get_param: use_config_drive }
      wait_handle_curl: { get_attr: [wait_handle_onboard, curl_cli] }
      wait_handle_curl_options: { get_param: os_heat_wc_notify_options }
      ua_allow: { get_param: allow_usage_analytics }
      ua_cloudlibs_tag: { get_param: f5_cloudlibs_tag }
      ua_project_id: { get_param: 'OS::project_id'}
      ua_stack_id: { get_param: 'OS::stack_id' }
      ua_template_name: sup-ex-dynamic-f5_bigip_standalone_1_nic.yaml
      ua_template_version: 3.1.0
      ua_license_type: { get_param: bigip_licensing_type }
  init_4_run_commands:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: dict(recurse_array,no_replace)+list(append)
        runcmd:
          - nohup /config/preOnboard.sh &>> /var/log/cloud/openstack/preOnboard.log < /dev/null &
          - nohup sh -c '/config/wait-cloudlibsInstall.sh; f5-rest-node /config/cloud/openstack/node_modules/@f5devcentral/f5-cloud-libs/scripts/runScript.js --file /config/encrypt.sh -o /var/log/cloud/openstack/encrypt.log' &>> /var/log/cloud/openstack/runScript.log < /dev/null &
          - nohup sh -c '/config/wait-cloudlibsInstall.sh; f5-rest-node /config/cloud/openstack/node_modules/@f5devcentral/f5-cloud-libs/scripts/runScript.js --file /config/onboard.sh --wait-for ENCR_DONE -o /var/log/cloud/openstack/onboard.log' &>> /var/log/cloud/openstack/runScript.log < /dev/null &
          - nohup sh -c '/config/wait-cloudlibsInstall.sh; f5-rest-node /config/cloud/openstack/node_modules/@f5devcentral/f5-cloud-libs/scripts/runScript.js --file /config/postOnboard.sh --wait-for ONBOARD_DONE -o /var/log/cloud/openstack/postOnboard.log' &>> /var/log/cloud/openstack/runScript.log < /dev/null &
  bigip_provision:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: {get_resource: init_1_override_default_config}
        - config: {get_resource: init_2_onboard_libs}
        - config: {get_resource: init_3_onboard_scripts}
        - config: {get_resource: init_4_run_commands}
  bigip_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: bigip_image }
      flavor: { get_param: bigip_flavor }
      key_name: { get_param: bigip_os_ssh_key }
      config_drive: { get_param: use_config_drive }
      networks:
        - port: {get_resource: mgmt_port}
      user_data_format: RAW
      user_data: {get_resource: bigip_provision}

outputs:
  bigip_instance_id:
    description: ID of the BIG-IP instance
    value: { get_resource: bigip_instance }
  bigip_instance_name:
    description: Name of the BIG-IP instance
    value: { get_attr: [bigip_instance, name] }
  floating_ip:
    description: The Floating IP address of the BIG-IP instance
    value: { get_attr: [floating_ip, floating_ip_address] }
  mgmt_ip:
    description: The mgmt IP address of BIG-IP instance
    value: { get_attr: [mgmt_port, fixed_ips, 0, ip_address] }
  mgmt_mac:
    description: The mgmt MAC address of BIG-IP instance
    value: { get_attr: [mgmt_port, mac_address] }
  mgmt_port_id:
    description: The port id of the BIG-IP mgmt interface
    value: { get_resource: mgmt_port }
