image: node:4

stages:
    - package
package:
    tags:
        - docker-executor
    stage: package
    only:
        - /^build-hash*/
        - /^release-.*/
        - triggers
    script:
        - tar -zcvf dist/f5-openstack-hot-supported.tar.gz supported
        - cd dist
        - openssl dgst -sha512 f5-openstack-hot-supported.tar.gz | cut -d ' ' -f 2
    artifacts:
        name: f5-openstack-hot-supported-$CI_COMMIT_SHA
        paths:
            - dist/

