heat_template_version: 2016-04-08

description: This template deploys standard security group to be associated with a BIG-IP Cluster/HA VLAN.

parameters:
  security_group_name:
    type: string
    label: Security Group Name
    description: The name of the Big-IP control security group

resources:
  bigip_control_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: security group rules for control interfaces
      name: { get_param: security_group_name }
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: udp
          port_range_min: 1026
          port_range_max: 1043
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 4353
          port_range_max: 4353

outputs:
  control_security_group_id:
    description: Get resource id of this security group
    value: { get_resource: bigip_control_security_group }
