heat_template_version: 2016-04-08

description: This template builds components for dynamic number of nics.

parameters:
  bigip_nic_count:
    type: number
    label: f5 BIG-IP NIC count
    description: Number of additional NICs to attach to the BIG-IP. Note - exclude management nic from count.
  network_vlan_names:
    type: comma_delimited_list
    label: OS Neutron Networks to map to the BIG-IP VLANs
    description: The Neutron Networks for the corresponding BIG-IP VLANs.
  network_vlan_subnets:
    type: comma_delimited_list
    label: OS Neutron Subnets to map to the BIG-IP VLANs
    description: The Neutron Subnets for the corresponding BIG-IP VLANs.
  network_vlan_security_group_ids:
    type: comma_delimited_list
    label: Security Group IDs
    description: The security group ids to associate with each Neutron port
  bigip_default_gateway:
    type: string
    label: Default Gateway IP
    description: Upstream Gateway IP Address for BIG-IP instance.
    default: None
  bigip_vlan_names:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN names
    description: Names of the VLAN to be created on the BIG-IP.
    default:
      -
  bigip_vlan_mtus:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN MTUs
    description: MTU values of the VLAN on the BIG-IP.
  bigip_vlan_tags:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN tags
    description: Tags to apply on the VLAN on the BIG-IP. Use default value "None" for untagged.
    default: None
  bigip_self_port_lockdowns:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN Allow Services Settings
    description: Optional list of <service:port> lockdown settings for the VLAN. If no value is supplied, default is used.
    default:
  wait_handle_curl:
    type: string
    label: Wait Handle Curl
    description: Resolved curl_cli value of the WaitConditionHandle that enables status signals to be sent back to Heat
  wait_handle_curl_options:
    type: string
    label: Wait Handle Curl Additional Options
    description: Additonal options to add to curl_cli value of the WaitConditionHandle that enables status signals to be sent back to Heat
    default: None


resources:

  network_vlan_ports:
    type: F5::BigIP::NeutronPorts
    properties:
      count: { get_param: bigip_nic_count }
      network_names: { get_param: network_vlan_names }
      network_subnets: { get_param: network_vlan_subnets }
      security_group_ids: { get_param: network_vlan_security_group_ids }

  onboard_network_config:
    type: F5::BigIP::OnboardNetworkConfigNNic
    properties:
      nic_count: { get_param: bigip_nic_count }
      vlan_names: { get_param: bigip_vlan_names }
      vlan_tags: { get_param: bigip_vlan_tags }
      vlan_mtus: { get_param: bigip_vlan_mtus }
      self_ip_addrs: { get_attr: [network_vlan_ports, bigip_self_ips_addresses] }
      self_cidr_blocks: { get_attr: [network_vlan_ports, bigip_self_ips_cidrs] }
      self_port_lockdowns: { get_param: bigip_self_port_lockdowns }
      default_gateway: { get_param: bigip_default_gateway }
      wait_handle_curl: { get_param: wait_handle_curl }
      wait_handle_curl_options: { get_param: wait_handle_curl_options }

  run_core_commands:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: dict(recurse_array,no_replace)+list(append)
        runcmd:
          - nohup sh -c '/config/preOnboard.sh' &>> /var/log/cloud/openstack/preOnboard.log < /dev/null &
          - nohup sh -c '/config/wait-cloudlibsInstall.sh; f5-rest-node /config/cloud/openstack/node_modules/@f5devcentral/f5-cloud-libs/scripts/runScript.js --file /config/encrypt.sh -o /var/log/cloud/openstack/encrypt.log' &>> /var/log/cloud/openstack/runScript.log < /dev/null &
          - nohup sh -c '/config/wait-cloudlibsInstall.sh; f5-rest-node /config/cloud/openstack/node_modules/@f5devcentral/f5-cloud-libs/scripts/runScript.js --file /config/onboard.sh --wait-for ENCR_DONE -o /var/log/cloud/openstack/onboard.log' &>> /var/log/cloud/openstack/onboard.log < /dev/null &
          - nohup sh -c '/config/wait-cloudlibsInstall.sh; f5-rest-node /config/cloud/openstack/node_modules/@f5devcentral/f5-cloud-libs/scripts/runScript.js --file /config/onboard-network.sh --wait-for ONBOARD_DONE --signal ONBOARD_NETWORK_DONE  -o /var/log/cloud/openstack/onboard-network.log' &>> /var/log/cloud/openstack/runScript.log < /dev/null &
          - nohup sh -c '/config/wait-cloudlibsInstall.sh; f5-rest-node /config/cloud/openstack/node_modules/@f5devcentral/f5-cloud-libs/scripts/runScript.js --file /config/postOnboard.sh --wait-for ONBOARD_NETWORK_DONE -o /var/log/cloud/openstack/postOnboard.log' &>> /var/log/cloud/openstack/runScript.log < /dev/null &

  run_core_commands_static_mgmt:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: dict(recurse_array,no_replace)+list(append)
        runcmd:
          - nohup sh -c '/config/wait-staticMgmtConfig.sh; /config/download-cloudlibs.sh' &>> /var/log/cloud/openstack/download-cloudlibs.log< /dev/null &
          - nohup sh -c '/config/wait-cloudlibsDownload.sh; /config/preOnboard.sh' &>> /var/log/cloud/openstack/preOnboard.log < /dev/null &
          - nohup sh -c '/config/wait-cloudlibsInstall.sh; f5-rest-node /config/cloud/openstack/node_modules/@f5devcentral/f5-cloud-libs/scripts/runScript.js --file /config/encrypt.sh -o /var/log/cloud/openstack/encrypt.log' &>> /var/log/cloud/openstack/runScript.log < /dev/null &
          - nohup sh -c '/config/wait-cloudlibsInstall.sh; f5-rest-node /config/cloud/openstack/node_modules/@f5devcentral/f5-cloud-libs/scripts/runScript.js --file /config/onboard.sh --wait-for ENCR_DONE -o /var/log/cloud/openstack/onboard.log' &>> /var/log/cloud/openstack/onboard.log < /dev/null &
          - nohup sh -c '/config/wait-cloudlibsInstall.sh; f5-rest-node /config/cloud/openstack/node_modules/@f5devcentral/f5-cloud-libs/scripts/runScript.js --file /config/onboard-network.sh --wait-for ONBOARD_DONE --signal ONBOARD_NETWORK_DONE  -o /var/log/cloud/openstack/onboard-network.log' &>> /var/log/cloud/openstack/runScript.log < /dev/null &
          - nohup sh -c '/config/wait-cloudlibsInstall.sh; f5-rest-node /config/cloud/openstack/node_modules/@f5devcentral/f5-cloud-libs/scripts/runScript.js --file /config/postOnboard.sh --wait-for ONBOARD_NETWORK_DONE -o /var/log/cloud/openstack/postOnboard.log' &>> /var/log/cloud/openstack/runScript.log < /dev/null &

outputs:
  ports_ids:
    value: { get_attr: [network_vlan_ports, neutron_ports_ids] }
  ports_fixed_ips:
    value: { get_attr: [network_vlan_ports, neutron_ports_fixed_ips] }
  ports_subnets:
    value: { get_attr: [network_vlan_ports, neutron_ports_subnets]}
  init_4_onboard_network_config:
    value: { get_resource: onboard_network_config }
  init_5_run_core_commands:
    value: { get_resource: run_core_commands }
  init_5_run_core_commands_static_mgmt:
    value: { get_resource: run_core_commands_static_mgmt }
  bigip_self_ips_addresses:
    value: { get_attr: [network_vlan_ports, bigip_self_ips_addresses] }
  bigip_self_ips_cidrs:
    value: { get_attr: [network_vlan_ports, bigip_self_ips_cidrs] }
  bigip_self_ips_masks:
    value: { get_attr: [network_vlan_ports, bigip_self_ips_masks] }
