heat_template_version: 2016-04-08

description: This template creates a standard neutron port to associate with a Big-IP instance. This template uses an index parameter that enables ports to be created as part of a resource group. 

parameters:
  index:
    type: number
    label: Port Index
    description: The index of the port in the group
  security_groups:
    type: json
  network_names:
    type: comma_delimited_list
  network_subnets:
    type: comma_delimited_list
  ip_addresses:
    type: comma_delimited_list

resources:
  bigip_neutron_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: [network_names, { get_param: index }] }
      security_groups: [{ get_param: [ security_groups, { get_param: index}] }]
      admin_state_up: true
      fixed_ips:
        - subnet: { get_param: [network_subnets, { get_param: index }] }
          ip_address: { get_param: [ip_addresses, { get_param: index }] }

outputs:
  bigip_neutron_port_id:
    value: {get_resource: bigip_neutron_port}
