heat_template_version: 2016-04-08

description: This template configures network components for a standard f5 standalone VE image.  

parameters:
  script_path:
    type: string
    label: Script Path
    description: Full path of the onboard network script
    default: /config/onboard-network.sh
  default_gateway:
    type: string
    label: Default Gateway IP
    description: Upstream Gateway IP Address for VE instances.
    default: None
  vlan_name:
    type: string
    label: f5 BIG-IP VE VLAN name
    description: Name of the VLAN to be created/referenced on the BIG-IP.
  vlan_create_new:
    type: boolean
    label: Creates a new VLAN on the BIG-IP
    default: true
  vlan_mtu:
    type: number
    label: f5 BIG-IP VE VLAN MTU
    description: MTU value of the VLAN on the BIG-IP.
    default: 0
  vlan_tag:
    type: string
    label: f5 BIG-IP VE VLAN tag
    description: Tag to apply on the VLAN on the BIG-IP. VLAN default is untagged. 
    default: None
  vlan_nic:
    type: string
    label: f5 BIG-IP VE VLAN NIC
    description: The NIC associated with the BIG-IP VLAN.
    default: "1.1"
  self_name:
    type: string
    label: f5 BIG-IP VE VLAN SelfIP Name
    default: None
  self_ip_addr:
    type: string
    label: f5 BIG-IP VE VLAN SelfIP Address
    description: Self-IP address to associate with the BIG-IP VLAN.
  self_cidr_block:
    type: string 
    label: f5 BIG-IP VE VLAN CIDR Block
    description: CIDR Block for the BIG-IP SelfIP address.
  self_port_lockdown:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN Allow Services
    description: Optional list of <service:port> lockdown settings for the VLAN. If no value is supplied, default port lockdown settings are used. 
    default:
      - 
  wait_handle_curl:
    type: string
    label: Wait Handle 
    description: Resolved curl_cli value of the WaitConditionHandle that enables status signals to be sent back to Heat

resources:
  onboard_network_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: dict(recurse_array,no_replace)+list(append)
        write_files:
        - path: { get_param: script_path }
          permissions: 0755
          owner: root:root
          content:
            str_replace:
              params:
                __default_gateway__: { get_param: default_gateway }
                __network_vlan_name__ : { get_param: vlan_name }
                __network_vlan_create__: { get_param: vlan_create_new }
                __network_vlan_tag__ : { get_param: vlan_tag}
                __network_vlan_mtu__ : { get_param: vlan_mtu }
                __network_vlan_nic__ : { get_param: vlan_nic }
                __network_vlan_nic_index__ : ""
                __network_vlan_last_nic_index__ : ""
                __network_self_name__ : { get_param: self_name }
                __network_self_ip_addr__ : { get_param: self_ip_addr }
                __network_self_cidr_block__ : { get_param: self_cidr_block }
                __network_self_port_lockdown__ :
                  list_join:
                  - ' '
                  -
                    repeat:
                      template: allowport
                      for_each:
                        allowport: { get_param: self_port_lockdown }
                wc_notify: { get_param: wait_handle_curl }
              template: { get_file: ../scripts/onboard-network.sh}
outputs:
  OS::stack_id:
    description: F5::BigIP::OnboardNetworkConfig resource.
    value:
      get_resource: onboard_network_config